[package]
name = "backstage_render"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
backstage_core.workspace = true
bytemuck.workspace = true
glam.workspace = true
lyon.workspace = true
wgpu.workspace = true

[dev-dependencies]
image.workspace = true
pollster.workspace = true
