[package]
name = "backstage_protocol"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
memmap2.workspace = true
postcard.workspace = true
serde.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
